---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: zdevops
data:
  redis-config: |
    appendonly yes
    protected-mode no
    dir /data
    port 6379
    requirepass redis@abc.com
